from exceptions import convert

def main():
    convert("two nine".split())
if __name__ == "__main__":
    main()